# Generated by Django 4.0.1 on 2022-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_movie.jpg', upload_to='movies_thumbnails'),
        ),
    ]
